### PR TITLE
Feature/create make file

### LINKED ISSUE #2: Create simple Makefile
Currently the README.md contains the necessary build, test and run commands.
These should be placed in a simple Makefile.

### PR DESCRIPTION
**Pull request by davelosert**
@aweisser : What do you think? Enough to start with or should I change something?

*EDIT*:
Fixes #2

### CODE REVIEW

**Review by aweisser — CHANGES_REQUESTED** [review]
- I don‘t think we need a windows build. ;)
- I‘d like to see some linting with gometalinter (see Readme.md).
- The rest is fine

**Comment by davelosert** [comment]
Alles klar. Ich mach das mal hier noch als Task Liste:
- [x] Delete Windows Build
- [x] Implement Linting

**Comment by davelosert** [comment]
Build is failing now because Metalinter doesn't seem to install all dependencies.. this is quite a pain. I will look into it later.

**Comment by aweisser** [comment]
did you executed gometalinter --install ?

**Comment by davelosert** [comment]
@aweisser Finally - everything is working. Linting is implemented. What do you think?

**Comment by aweisser** [comment]
There are conflicts. Pls rebase

**Review by aweisser — APPROVED** [review]

**Pull request merged**
